#!/usr/bin/env bash
set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

log() { printf "[%s] %s\n" "$(date +%T)" "$*"; }
warn() { printf "${YELLOW}[WARN]${NC} %s\n" "$*"; }
err() { printf "${RED}[ERROR]${NC} %s\n" "$*" >&2; }
info() { printf "${BLUE}[INFO]${NC} %s\n" "$*"; }

# SIGINT Trap
cleanup() {
    warn "Interrupted – cleaning up temporary files"
    rm -f /tmp/stratoshell_site.yml /tmp/stratoshell_inventory.ini
    rm -rf /tmp/stratoshell_templates
    exit 1
}
trap cleanup SIGINT SIGTERM

# Disclaimer
clear
echo -e "${BOLD}${BLUE}========================================${NC}"
echo -e "${BOLD}${BLUE}  StratoShell Module 03 – OS Provisioner${NC}"
echo -e "${BOLD}${BLUE}========================================${NC}"
echo ""
echo -e "${BOLD}${RED}DISCLAIMER:${NC} This module generates a standardized Ansible Playbook for"
echo -e "multi-distro enterprise OS baseline provisioning."
echo -e "Supported: ${GREEN}Ubuntu 22.04, 24.04, 26.04${NC} | ${GREEN}RHEL 8.x, 9.x, 10.x${NC}"
echo ""

# Variables
TIME_ZONE=""
DNS_PRIMARY=""
DNS_SECONDARY=""
SSH_PORT=22
DELIVERY_MODE=""
OUTPUT_DIR=""
GITLAB_API_URL=""
GITLAB_TOKEN=""
GITLAB_PROJECT_ID=""
GITLAB_BRANCH="main"
NTP_SERVERS=""

# Valid IP regex
IP_REGEX='^([0-9]{1,3}\.){3}[0-9]{1,3}$'

# Input: Time Zone
while [[ -z "$TIME_ZONE" ]]; do
    read -rp "Target Time Zone (e.g., Asia/Tehran, UTC): " TIME_ZONE
    [[ -z "$TIME_ZONE" ]] && warn "Time zone cannot be empty"
done

# Input: Custom NTP Servers
while [[ -z "$NTP_SERVERS" ]]; do
    read -rp "Enter NTP servers separated by commas or spaces (e.g., 0.pool.ntp.org, 1.pool.ntp.org): " NTP_SERVERS
    [[ -z "$NTP_SERVERS" ]] && warn "NTP servers list cannot be empty"
done

# Parse NTP servers into array (handle both comma and space separated)
NTP_ARRAY=()
IFS=', ' read -ra SERVERS <<< "$NTP_SERVERS"
for s in "${SERVERS[@]}"; do
    [[ -n "$s" ]] && NTP_ARRAY+=("$s")
done

# Input: Primary DNS
while [[ -z "$DNS_PRIMARY" ]]; do
    read -rp "Primary DNS Server (IP): " DNS_PRIMARY
    if [[ ! $DNS_PRIMARY =~ $IP_REGEX ]]; then
        warn "Invalid IP format for Primary DNS"
        DNS_PRIMARY=""
    fi
done

# Input: Secondary DNS
while [[ -z "$DNS_SECONDARY" ]]; do
    read -rp "Secondary DNS Server (IP): " DNS_SECONDARY
    if [[ ! $DNS_SECONDARY =~ $IP_REGEX ]]; then
        warn "Invalid IP format for Secondary DNS"
        DNS_SECONDARY=""
    fi
done

# Input: SSH Port
read -rp "Custom SSH Port [22]: " input_port
SSH_PORT=${input_port:-22}
[[ "$SSH_PORT" =~ ^[0-9]+$ ]] || { warn "Invalid port, using 22"; SSH_PORT=22; }

# Delivery Mode
echo ""
echo "Select delivery method:"
echo "  A) Save locally to a directory"
echo "  B) Upload to GitLab (API)"
while [[ -z "$DELIVERY_MODE" ]]; do
    read -rp "Choice [A/B]: " choice
    case ${choice^^} in
        A) DELIVERY_MODE="local" ;;
        B) DELIVERY_MODE="gitlab" ;;
        *) warn "Invalid choice" ;;
    esac
done

if [[ "$DELIVERY_MODE" == "local" ]]; then
    while [[ -z "$OUTPUT_DIR" ]]; do
        read -rp "Output directory path: " OUTPUT_DIR
        mkdir -p "$OUTPUT_DIR" 2>/dev/null || { warn "Cannot create directory"; OUTPUT_DIR=""; }
    done
else
    while [[ -z "$GITLAB_API_URL" ]]; do
        read -rp "GitLab API URL (e.g., https://gitlab.com/api/v4): " GITLAB_API_URL
    done
    while [[ -z "$GITLAB_TOKEN" ]]; do
        read -rsp "GitLab Private Access Token: " GITLAB_TOKEN; echo
    done
    while [[ -z "$GITLAB_PROJECT_ID" ]]; do
        read -rp "GitLab Project ID: " GITLAB_PROJECT_ID
    done
    read -rp "Target Branch [main]: " GITLAB_BRANCH
    GITLAB_BRANCH=${GITLAB_BRANCH:-main}
fi

# Generate inventory.ini
cat > /tmp/stratoshell_inventory.ini <<INV
[ubuntu]
# ubuntu22 ansible_host=10.0.0.1 ansible_user=ubuntu
# ubuntu24 ansible_host=10.0.0.2 ansible_user=ubuntu

[rhel]
# rhel8 ansible_host=10.0.0.3 ansible_user=root
# rhel9 ansible_host=10.0.0.4 ansible_user=root

[all:vars]
ansible_ssh_port=$SSH_PORT
ansible_python_interpreter=auto_silent
timezone=$TIME_ZONE
dns_primary=$DNS_PRIMARY
dns_secondary=$DNS_SECONDARY
ntp_servers=$(IFS=','; echo "${NTP_ARRAY[*]}")
INV

# Create templates directory
mkdir -p /tmp/stratoshell_templates

# Generate chrony.conf.j2 template
cat > /tmp/stratoshell_templates/chrony.conf.j2 <<'EOF'
# Chrony Configuration - Generated by StratoShell Module 03
# Managed by Ansible - Do not edit manually

{% if ntp_servers is defined and ntp_servers | length > 0 %}
{% for server in ntp_servers.split(',') %}
server {{ server }} iburst
{% endfor %}
{% else %}
# Fallback pools if no custom NTP servers provided
server 0.pool.ntp.org iburst
server 1.pool.ntp.org iburst
server 2.pool.ntp.org iburst
server 3.pool.ntp.org iburst
{% endif %}

# Allow NTP client access from local network
allow 192.168.0.0/16
allow 10.0.0.0/8
allow 172.16.0.0/12

# Serve time even if not synchronized to a time source
local stratum 10

# Record the rate at which the system clock gains/losses time
driftfile /var/lib/chrony/drift

# Enable kernel synchronization of the real-time clock (RTC)
rtcsync

# Step the system clock instead of slewing it if the adjustment is larger than 1 second
makestep 1.0 3

# Enable hardware timestamping on all interfaces that support it
hwtimestamp *

# Increase the minimum number of selectable sources required to adjust the clock
minsources 1

# Allow the clock to be stepped on boot
# Max allowed distance from the reference time before chrony gives up
maxdistance 3
EOF

# Generate resolv.conf.j2 template
cat > /tmp/stratoshell_templates/resolv.conf.j2 <<'EOF'
# Resolv.conf Configuration - Generated by StratoShell Module 03
# Managed by Ansible - Do not edit manually

nameserver {{ dns_primary }}
nameserver {{ dns_secondary }}
# fallback
nameserver 1.1.1.1
nameserver 8.8.8.8

options timeout:2 attempts:1 rotate single-request-reopen
EOF

# Generate site.yml
cat > /tmp/stratoshell_site.yml <<'YAML'
---
- name: Enterprise OS Baseline Provisioning
  hosts: all
  become: true
  gather_facts: true
  vars:
    timezone: "{{ timezone | default('UTC') }}"
    dns_primary: "{{ dns_primary | default('1.1.1.1') }}"
    dns_secondary: "{{ dns_secondary | default('8.8.8.8') }}"
    ntp_servers: "{{ ntp_servers | default('0.pool.ntp.org,1.pool.ntp.org,2.pool.ntp.org,3.pool.ntp.org') }}"
    file_limits:
      soft: 65536
      hard: 65536

  pre_tasks:
    - name: Detect distribution family
      set_fact:
        is_debian: "{{ ansible_os_family == 'Debian' }}"
        is_redhat: "{{ ansible_os_family == 'RedHat' }}"

  tasks:
    # --- Time & NTP ---
    - name: Install chrony (Debian)
      apt:
        name: chrony
        state: present
        update_cache: true
      when: is_debian

    - name: Install chrony (RHEL)
      dnf:
        name: chrony
        state: present
      when: is_redhat

    - name: Configure chrony with custom NTP servers
      template:
        src: templates/chrony.conf.j2
        dest: /etc/chrony/chrony.conf
        mode: '0644'
      notify: restart chrony

    - name: Configure chrony for RHEL path
      template:
        src: templates/chrony.conf.j2
        dest: /etc/chrony.conf
        mode: '0644'
      when: is_redhat
      notify: restart chrony

    - name: Set system timezone
      community.general.timezone:
        name: "{{ timezone }}"

    # --- Disable Non-Essential Services ---
    - name: Disable non-essential services (Debian)
      systemd:
        name: "{{ item }}"
        enabled: false
        state: stopped
        masked: true
      loop:
        - postfix
        - bluetooth
        - cups
        - avahi-daemon
      when: is_debian
      ignore_errors: true

    - name: Disable non-essential services (RHEL)
      systemd:
        name: "{{ item }}"
        enabled: false
        state: stopped
        masked: true
      loop:
        - postfix
        - bluetooth
        - cups
        - avahi-daemon
      when: is_redhat
      ignore_errors: true

    # --- Firewall ---
    - name: Disable UFW (Debian)
      ufw:
        state: disabled
      when: is_debian
      ignore_errors: true

    - name: Disable firewalld (RHEL)
      systemd:
        name: firewalld
        enabled: false
        state: stopped
        masked: true
      when: is_redhat
      ignore_errors: true

    # --- SELinux (RHEL) ---
    - name: Set SELinux to permissive (runtime)
      command: setenforce 0
      when: is_redhat
      ignore_errors: true
      changed_when: false

    - name: Set SELinux to disabled (persistent)
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
      when: is_redhat

    # --- DNS Configuration ---
    - name: Write resolv.conf with custom DNS (systemd-resolved disabled)
      template:
        src: templates/resolv.conf.j2
        dest: /etc/resolv.conf
        mode: '0644'
      when: not is_redhat or ansible_distribution_major_version|int >= 8

    - name: Configure NetworkManager DNS (RHEL 8+)
      block:
        - name: Ensure NetworkManager.d directory
          file:
            path: /etc/NetworkManager/conf.d
            state: directory
            mode: '0755'
          when: is_redhat

        - name: Set NetworkManager DNS
          lineinfile:
            path: /etc/NetworkManager/conf.d/99-dns.conf
            line: "dns={{ dns_primary }},{{ dns_secondary }}"
            create: true
            mode: '0644'
          when: is_redhat

    # --- File Limits ---
    - name: Set file descriptor limits
      lineinfile:
        path: /etc/security/limits.conf
        line: "*          hard    nofile          {{ file_limits.hard }}"
        state: present
        create: true

    - name: Set file descriptor limits (soft)
      lineinfile:
        path: /etc/security/limits.conf
        line: "*          soft    nofile          {{ file_limits.soft }}"
        state: present

  handlers:
    - name: restart chrony
      systemd:
        name: "{{ 'chronyd' if is_redhat else 'chrony' }}"
        state: restarted
        enabled: true

YAML

# Delivery
if [[ "$DELIVERY_MODE" == "local" ]]; then
    cp /tmp/stratoshell_site.yml "$OUTPUT_DIR/site.yml"
    cp /tmp/stratoshell_inventory.ini "$OUTPUT_DIR/inventory.ini"
    cp -r /tmp/stratoshell_templates "$OUTPUT_DIR/templates"
    info "Playbook saved to: $OUTPUT_DIR"
else
    info "GitLab API upload placeholder - implement curl to GitLab API"
    info "Files prepared in /tmp/stratoshell_*"
fi

# Summary Screen
clear
echo -e "${BOLD}${BLUE}========================================${NC}"
echo -e "${BOLD}${BLUE}  Provisioner Configuration Summary${NC}"
echo -e "${BOLD}${BLUE}========================================${NC}"
echo ""
echo -e "${BOLD}Target Timezone:${NC} $TIME_ZONE"
echo -e "${BOLD}Custom NTP Servers:${NC} ${NTP_ARRAY[*]}"
echo -e "${BOLD}Primary DNS:${NC} $DNS_PRIMARY"
echo -e "${BOLD}Secondary DNS:${NC} $DNS_SECONDARY"
echo -e "${BOLD}SSH Port:${NC} $SSH_PORT"
echo -e "${BOLD}Delivery Mode:${NC} $DELIVERY_MODE"
if [[ "$DELIVERY_MODE" == "local" ]]; then
    echo -e "${BOLD}Output Directory:${NC} $OUTPUT_DIR"
else
    echo -e "${BOLD}GitLab API:${NC} $GITLAB_API_URL"
    echo -e "${BOLD}GitLab Project:${NC} $GITLAB_PROJECT_ID"
    echo -e "${BOLD}GitLab Branch:${NC} $GITLAB_BRANCH"
fi
echo ""
echo -e "${BOLD}${BLUE}========================================${NC}"
echo -e "${BOLD}${GREEN}Files generated successfully.${NC}"
echo -e "${BOLD}${BLUE}========================================${NC}"
echo ""
echo "To execute the playbook:"
echo "  ansible-playbook -i inventory.ini site.yml -K"
echo ""

# Cleanup temp files
rm -f /tmp/stratoshell_site.yml /tmp/stratoshell_inventory.ini
rm -rf /tmp/stratoshell_templates